# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mingzhang Yin
tagline:          'A Jekyll theme'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'

description:      Mingzhang (Michael) Yin's homepage. 
                  mzyin AT utexas DOT edu
url:              https://mingzhangyin.com
#baseurl:          /

author:
  name:           'Mingzhang Yin'
  url:            https://mingzhangyin.com

paginate:         3


version:          2.1.0

github:
  repo:           https://github.com/mingzhang-yin
