#name: Hank Quinlan, Horrible Cop
markdown: kramdown
theme: minima
url: "http://mingzhang-yin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
